const LIST_BREEDS = 'LIST_BREEDS'
const API_LIST_BREEDS_SUCCESS = 'API_LIST_BREEDS_SUCCESS'
const LIST_BREED_IMAGES = 'LIST_BREED_IMAGES'
const API_LIST_BREED_IMAGES_SUCCESS = 'API_LIST_BREED_IMAGES_SUCCESS'

export {
    LIST_BREEDS,
    LIST_BREED_IMAGES,
    API_LIST_BREEDS_SUCCESS,
    API_LIST_BREED_IMAGES_SUCCESS
}
